version: '2'

services:
  heimdall:
    container_name: heimdall
    image: linuxserver/heimdall
    environment:
      - TZ=Europe/Madrid
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./conf:/config
