---
- name: Copy notification script
  copy:
    src: notification-startup.sh
    dest: /usr/local/bin

- name: Provide execution permissions to scripts
  file:
    dest: "{{ item }}"
    mode: a+x
  loop:
    - /usr/local/bin/notification-startup.sh

- name: Copy notification timer files
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system
  loop:
    - notification-startup.service
    - notification-startup.timer

- name: Force systemd to reload configs
  systemd:
    daemon_reload: yes

- name: Enable notification timers
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - startup-notification.timer

# TODO: delete unnecessary files call startup-notification.{sh,service,timer}
