---
- fail:
    msg: "telegram.chatid and telegram.token variables must be defined in order to use notification-startup.sh.j2 template!!"
  when: not telegram or not telegram.chatid or not telegram.token

- name: Copy notification script
  template:
    src: notification-startup.sh.j2
    dest: /usr/local/bin/notification-startup.sh
    mode: a+x

- name: Copy notification timer files
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/system
  loop:
    - notification-startup.service
    - notification-startup.timer

- name: Force systemd to reload configs
  systemd:
    daemon_reload: yes

- name: Enable notification timers
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - startup-notification.timer

# TODO: delete unnecessary files call startup-notification.{sh,service,timer}
