version: '2'

services:
  grafana-server:
    container_name: grafana-server
    image: grafana/grafana:latest
    networks:
      - dashboard
    restart: unless-stopped
    volumes:
      - ./conf/grafana.ini:/etc/docker/grafana/grafana.ini
      - logs:/var/log/grafana/grafana.log
      - data:/var/lib/grafana
      - home:/usr/share/grafana
      - plugins:/var/lib/grafana/plugins
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards

volumes:
  data:

  home:

  logs:

  plugins:

  provisioning:

networks:
  dashboard:
    external: true
