---
- name: Create Heimdall folder
  file:
    path: /etc/docker/heimdall/conf
    state: directory

- name: Deploy Heimdall container
  include_tasks: docker_heimdall.yml

- name: Add Heimdall password protection
  command: >-
    docker exec -i heimdall htpasswd -i -c /config/nginx/.htpasswd {{ htusr|quote }}
  args:
    stdin: "{{ htpasswd }}"
  when: htusr and htpasswd
