version: '2'
services:

  proxy:
    image: nginx-rev-proxy
    volumes:
      - /etc/ssl/:/etc/ssl/:ro
    ports:
      - 1000:1000
      - 1001:1001
    networks:
      - reverse-proxy

  grafana-server:
    image: grafana/grafana
    volumes:
      - /etc/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /var/lib/grafana:/var/lib/grafana
      - /usr/share/grafana:/usr/share/grafana
      - /var/log/grafana:/var/log/grafana
      - /var/lib/grafana/plugins:/var/lib/grafana/plugins
      - /etc/grafana/provisioning:/etc/grafana/provisioning
    ports: 
      - 3000:3000
    networks:
      - reverse-proxy

  prometheus-metrics:
    image: prometheus-met
    networks:
      - reverse-proxy

  networks:
    reverse-proxy:
      external:
        name: reverse-proxy
